baseurl:
url: "http://imcczy.com"
name: imcczy
author: imcczy
email: imcczyh@gmail.com
permalink: :title.html
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks]
JB :
  categories_path: categories.html
