baseurl:
url: "http://imcczy.com"
name: imcczy
author: imcczy
email: imcczyh@gmail.com
permalink: :title.html
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
JB :
  categories_path: categories.html
